import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google';
import './assets/css/globals.css';
import './assets/css/plugins.css';
import './assets/css/style.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'James Ryan',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} pilling-page nill-dark`}
        data-spy="scroll"
        data-target="#scrollspy"
        data-offset="1"
      >
        {children}
        <script src="./assets/js/script.js"></script>
        <Analytics />
      </body>
    </html>
  );
}
